environment:
  TWINE_USERNAME: michael.sanders
  # Note: TWINE_PASSWORD is set in Appveyor settings.
  matrix:
    # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc
      CIBW_SKIP: "*win32* cp33-* cp34-*"
      CIBW_BEFORE_BUILD: call scripts/appveyor.cmd
    # Stable 32-bit MSVC
    - channel: stable
      target: i686-pc-windows-msvc
      CIBW_SKIP: "*win_amd64* cp33-* cp34-*"
      CIBW_BEFORE_BUILD: call scripts/appveyor.cmd


# From https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain nightly --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - pip install -U pip --user
  - pip install cibuildwheel==0.9.4 setuptools-rust==0.10.3

build_script:
  - cargo update -p pyo3 --precise "0.5.0-alpha.1"
  - cibuildwheel --output-dir wheelhouse
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    python -m pip install twine
    &&
    @python -m twine upload "wheelhouse/*.whl" --username %TWINE_USERNAME% --password %TWINE_PASSWORD%
    )
  - >
    IF "%APPVEYOR_REPO_BRANCH%" == "master"
    (
    IF [%APPVEYOR_PULL_REQUEST_HEAD_COMMIT%] == []
    (
    python -m pip install twine
    &&
    @python -m twine upload "wheelhouse/*.whl" --repository-url https://test.pypi.org/legacy/ --username %TWINE_USERNAME% --password %TWINE_TEST_PASSWORD%
    )
    )

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
