[package]
name = "autopy"
version = "0.1.0"
authors = ["Michael Sanders <michael.sanders@fastmail.com>"]

[lib]
## Python extension modules should be compiled as 'cdylib'
crate-type = ["cdylib"]
name = "autopy"

[dependencies.autopilot]
version = "0.1.7"

[dependencies.pyo3]
version = "0.5.0-alpha.1"
default-features = false

[dependencies.image]
version = "0.19"

[dependencies.either]
version = "1.5.0"

[replace]
"autopilot:0.1.7" = { git = "https://github.com/autopilot-rs/autopilot-rs", branch = "master" }
